# stickler-ci configuration
linters:
    flake8:
       python: 3
       ignore: 'E501, E203, W503'
       max-line-length: 88
       fixer: false

review:
    # Don't use 'failure' build status when
    # a pull request contains style errors.
    fail_on_comments: false


