language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

virtualenv:
system_site_packages: true
 
before_install:
  - sudo apt-get update
  
# command to install dependencies
install:
  - pip install matplotlib
  - pip install scipy
  - pip install sympy

script:
  - nosetests 
