name: Publish to TestPyPI

on: push

jobs:
  build-n-publish:
    name: Publish RT1 to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          build: true
          # only upload if a tag is pushed (otherwise just build & check)
          url: https://test.pypi.org/legacy/
          upload: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}



    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    # - name: Publish distribution 📦 to PyPI
    #   if: startsWith(github.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}


# on:
#   workflow_run:
#     workflows: ["RT1_ubuntu"]
#     branches: [master]
#     types:
#       - completed
#       - requested