name: Publish to TestPyPI

on:
  push:
  # # trigger only on release
  # release:
  #   types: [created]
  # # to trigger workflow manually from actions-tab
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: "install packages"
        run: |
          # Upgrade pip
          python -m pip install --upgrade pip
          # Install build dependencies
          python -m pip install setuptools wheel twine

      # Upload to TestPyPI
      - name: Build and Upload to TestPyPI
        run: |
          python setup.py sdist bdist_wheel
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
          TWINE_REPOSITORY: testpypi

      - name: Test build on TestPyPI
        run: |
          VERSION=$(python setup.py --version)
          python -m pip install -i https://test.pypi.org/simple/ rt1==VERSION
          python -c "exec(\"import rt1\nprint('successfully imported RT1 v', rt1.__version__)\")"